[project]
name = "cs1302-code-visualizer"
version = "0.5.0"
description = "Visualize Java program memory state and output a screenshot."
authors = [
    {name = "Gabe Livengood", email = "timothy.livengood@uga.edu"},
    {name = "Michael E. Cotterell", email = "mepcott@uga.edu"},
]
maintainers = [
    {name = "Michael E. Cotterell", email = "mepcott@uga.edu"},
    {name = "Bradley J. Barnes", email = "bjb211@uga.edu"},
]
license = "MIT"
license-files = [
    "LICEN[CS]E*",
    "cs1302_code_visualizer/frontend/LICENSE",
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.0.0",
    "packaging>=24.0",
    "pillow>=11.2.1",
    "platformdirs>=4.3.8",
    "requests>=2.32.4",
    "rich>=14.3.3",
    "selenium>=4.33.0",
    "typer>=0.12.0",
]

[tool.cs1302-code-visualizer]
tracer-url  = "https://github.com/cs1302uga/cs1302-tracer/releases/download/v2.3.0/code-tracer.jar"
tracer-sha256 = "852f9b2f21093ec927743656266a66b0da6b9301f0d05fb7f85614a3b0e3e65d"

[tool.cs1302book.system-dependencies]
system-dependencies = [
    "enchant>=2.8.0,<3",
    "graphviz>=15.1.0",
    "plantuml>=1.2026.1,<1.2027",
    "jdk>=25,<26",
    "uv>=0.11.0",
]

[project.scripts]
generate_trace = "cs1302_code_visualizer.trace_generator:main"
generate_visualization = "cs1302_code_visualizer.browser_driver:main"
install-deps = "scripts.install_deps:main"
install-enchant = "scripts.installer.enchant:main"
install-graphviz = "scripts.installer.graphviz:main"
install-jdk = "scripts.installer.jdk:main"
install-plantuml = "scripts.installer.plantuml:main"
install-uv = "scripts.installer.uv:main"
list_breakpoints = "cs1302_code_visualizer.breakpoint_lister:main"
render_image = "cs1302_code_visualizer:main"

[tool.basedpyright]
reportAny = false
reportExplicitAny = false
reportImportCycles = false

[tool.ruff]
line-length = 100
indent-width = 4
preview = true
show-fixes = true

[tool.ruff.analyze]
type-checking-imports = true

[tool.ruff.format]
indent-style = "space"
preview = true
quote-style = "double"
skip-magic-trailing-comma = false

[tool.ruff.lint]
extend-select = ["D", "F401", "I", "TID", "Q"]
future-annotations = true
preview = true

[tool.ruff.lint.pycodestyle]
max-line-length = 100

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "--cov=cs1302_code_visualizer --cov-report=term-missing --cov-fail-under=100"
filterwarnings = [
    "ignore:.*found in sys.modules after import of package.*:RuntimeWarning",
]

[tool.coverage.report]
fail_under = 100
show_missing = true

[tool.ruff.lint.pydocstyle]
convention = "google"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "basedpyright>=1.39.0",
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
    "ruff>=0.15.9",
]
